affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 5
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
  - x
  - '0'
  - x
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
- - '0'
  - x
  - '0'
  - x
  - x
  - x
  - '0'
- - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
- - log
  - log
  - x
  - log
  - x
  - x
  - exp
symbolic.funs_name.1:
- - x
  - x
  - x
  - x
  - tanh
symbolic_enabled: true
width:
- - 7
  - 0
- - 5
  - 0
- - 1
  - 0
